Repository IOSD/IOSD-BPIT-Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#16 Login Page (HTML, CSS, Bootstrap)
  Web Dev/Frontend/Login/login.css
  Web Dev/Frontend/Login/login.html
  Web Dev/Frontend/README.md
Labels: hacktoberfest, hacktoberfest2022

#22 Depth First Search.cpp
  Programming and Algorithms/Depth First Search.cpp
Labels: hacktoberfest-accepted

#24 Added a Blog Website
  Web Dev/Full Stack/Blog/.gitignore
  Web Dev/Full Stack/Blog/Readme.md
  Web Dev/Full Stack/Blog/app.js
  Web Dev/Full Stack/Blog/data/database.js
  Web Dev/Full Stack/Blog/package-lock.json
  Web Dev/Full Stack/Blog/package.json
  Web Dev/Full Stack/Blog/public/styles/base.css
  Web Dev/Full Stack/Blog/public/styles/forms.css
  Web Dev/Full Stack/Blog/public/styles/posts.css
  Web Dev/Full Stack/Blog/routes/blog.js
  Web Dev/Full Stack/Blog/views/404.ejs
  Web Dev/Full Stack/Blog/views/500.ejs
  Web Dev/Full Stack/Blog/views/create-post.ejs
  Web Dev/Full Stack/Blog/views/includes/head.ejs
  Web Dev/Full Stack/Blog/views/includes/header.ejs
  Web Dev/Full Stack/Blog/views/includes/post-item.ejs
  Web Dev/Full Stack/Blog/views/post-detail.ejs
  Web Dev/Full Stack/Blog/views/posts-list.ejs
  Web Dev/Full Stack/Blog/views/update-post.ejs
  Web Dev/Full Stack/Readme.md
Labels: hacktoberfest-accepted

#28 avd30 added bubble Sort
  sorting/bubbleSort.cpp
Labels: hacktoberfest-accepted

#32 Create check_monotonic_array.py
  Programming and Algorithms/Python/check_monotonic_array.py
Labels: hacktoberfest-accepted

#34 Added a random dices project
  App Dev/iOS/random_dices_oddEven/random_dices.xcodeproj/project.pbxproj
  App Dev/iOS/random_dices_oddEven/random_dices.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  App Dev/iOS/random_dices_oddEven/random_dices.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  App Dev/iOS/random_dices_oddEven/random_dices.xcodeproj/project.xcworkspace/xcuserdata/apple.xcuserdatad/UserInterfaceState.xcuserstate
  App Dev/iOS/random_dices_oddEven/random_dices.xcodeproj/xcuserdata/apple.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  App Dev/iOS/random_dices_oddEven/random_dices.xcodeproj/xcuserdata/apple.xcuserdatad/xcschemes/xcschememanagement.plist
  App Dev/iOS/random_dices_oddEven/random_dices/AppDelegate.swift
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AccentColor.colorset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/1024.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/114.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/120.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/180.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/29.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/40.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/57.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/58.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/60.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/80.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/87.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/AppIcon.appiconset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFive.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFive.imageset/dice5.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFive.imageset/dice5@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFive.imageset/dice5@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFour.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFour.imageset/dice4.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFour.imageset/dice4@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceFour.imageset/dice4@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceOne.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceOne.imageset/dice1.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceOne.imageset/dice1@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceOne.imageset/dice1@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceSix.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceSix.imageset/dice6.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceSix.imageset/dice6@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceSix.imageset/dice6@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceThree.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceThree.imageset/dice3.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceThree.imageset/dice3@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceThree.imageset/dice3@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceTwo.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceTwo.imageset/dice2.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceTwo.imageset/dice2@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceTwo.imageset/dice2@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceeLogo.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceeLogo.imageset/diceeLogo.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceeLogo.imageset/diceeLogo@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/DiceeLogo.imageset/diceeLogo@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/GreenBackground.imageset/Contents.json
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/GreenBackground.imageset/newbackground.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/GreenBackground.imageset/newbackground@2x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Assets.xcassets/GreenBackground.imageset/newbackground@3x.png
  App Dev/iOS/random_dices_oddEven/random_dices/Base.lproj/LaunchScreen.storyboard
  App Dev/iOS/random_dices_oddEven/random_dices/Base.lproj/Main.storyboard
  App Dev/iOS/random_dices_oddEven/random_dices/Info.plist
  App Dev/iOS/random_dices_oddEven/random_dices/SceneDelegate.swift
  App Dev/iOS/random_dices_oddEven/random_dices/ViewController.swift
Labels: hacktoberfest-accepted

#35 A basic app which displays content on the screen
  App Dev/iOS/I Am Poor/I Am Poor.xcodeproj/project.pbxproj
  App Dev/iOS/I Am Poor/I Am Poor.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  App Dev/iOS/I Am Poor/I Am Poor.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  App Dev/iOS/I Am Poor/I Am Poor.xcodeproj/project.xcworkspace/xcuserdata/apple.xcuserdatad/UserInterfaceState.xcuserstate
  App Dev/iOS/I Am Poor/I Am Poor.xcodeproj/xcuserdata/apple.xcuserdatad/xcschemes/xcschememanagement.plist
  App Dev/iOS/I Am Poor/I Am Poor/AppDelegate.swift
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/AccentColor.colorset/Contents.json
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/AppIcon.appiconset/Contents.json
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/Contents.json
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/coal.imageset/Contents.json
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/coal.imageset/coal.png
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/coal.imageset/coal@2x.png
  App Dev/iOS/I Am Poor/I Am Poor/Assets.xcassets/coal.imageset/coal@3x.png
  App Dev/iOS/I Am Poor/I Am Poor/Base.lproj/LaunchScreen.storyboard
  App Dev/iOS/I Am Poor/I Am Poor/Base.lproj/Main.storyboard
  App Dev/iOS/I Am Poor/I Am Poor/Info.plist
  App Dev/iOS/I Am Poor/I Am Poor/SceneDelegate.swift
  App Dev/iOS/I Am Poor/I Am Poor/ViewController.swift
Labels: hacktoberfest-accepted

#36 An iconic I Am Rich app
  App Dev/iOS/I Am Rich/I Am Rich.xcodeproj/project.pbxproj
  App Dev/iOS/I Am Rich/I Am Rich.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  App Dev/iOS/I Am Rich/I Am Rich.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  App Dev/iOS/I Am Rich/I Am Rich.xcodeproj/project.xcworkspace/xcuserdata/apple.xcuserdatad/UserInterfaceState.xcuserstate
  App Dev/iOS/I Am Rich/I Am Rich.xcodeproj/xcuserdata/apple.xcuserdatad/xcschemes/xcschememanagement.plist
  App Dev/iOS/I Am Rich/I Am Rich/AppDelegate.swift
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AccentColor.colorset/Contents.json
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/100.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/1024.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/114.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/120.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/144.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/152.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/167.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/180.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/20.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/29.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/40.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/50.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/57.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/58.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/60.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/72.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/76.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/80.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/87.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/AppIcon.appiconset/Contents.json
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/Contents.json
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/Image.imageset/Contents.json
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/Image.imageset/diamond.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/Image.imageset/diamond@2x.png
  App Dev/iOS/I Am Rich/I Am Rich/Assets.xcassets/Image.imageset/diamond@3x.png
  App Dev/iOS/I Am Rich/I Am Rich/Base.lproj/LaunchScreen.storyboard
  App Dev/iOS/I Am Rich/I Am Rich/Base.lproj/Main.storyboard
  App Dev/iOS/I Am Rich/I Am Rich/Info.plist
  App Dev/iOS/I Am Rich/I Am Rich/SceneDelegate.swift
  App Dev/iOS/I Am Rich/I Am Rich/ViewController.swift
Labels: hacktoberfest-accepted

#38 count zeros in an array
  Programming and Algorithms/Cpp/Array/count_zeros.cpp.webloc
Labels: hacktoberfest-accepted

#40 Added Tower of Hanoi code in C++
  Programming and Algorithms/Tower of Hanoi in C++
Labels: hacktoberfest-accepted

#41 Added code for Palindrome Number
  Programming and Algorithms/Palindrome Number
Labels: hacktoberfest-accepted

#43 Added Stock Price Prediction
  AI and ML/Stock Price Prediction/Google_Stock_Price_Test.csv
  AI and ML/Stock Price Prediction/Google_Stock_Price_Train.csv
  AI and ML/Stock Price Prediction/RNN.ipynb
  AI and ML/Stock Price Prediction/readme.md
Labels: hacktoberfest-accepted

#44 User Input in Bubble Sort
  sorting/bubbleSort.cpp
Labels: hacktoberfest-accepted

#46 Adding Parallax
  Web Dev/parallax_effect/1.png
  Web Dev/parallax_effect/2.png
  Web Dev/parallax_effect/3.png
  Web Dev/parallax_effect/4.png
  Web Dev/parallax_effect/main.html
Labels: hacktoberfest-accepted

#47 Mirror Number Pattern
  Programming and Algorithms/Python/Mirror_Number_Pattern.cpp
Labels: hacktoberfest-accepted

#52 Rename Programming and Algorithms/Tower of Hanoi in C++ to Programmin…
  Programming and Algorithms/Cpp/Tower of Hanoi in C++
Labels: hacktoberfest-accepted

#51 Rename Programming and Algorithms/Palindrome Number to Programming an…
  Programming and Algorithms/java/Palindrome Number
Labels: hacktoberfest-accepted

#50 Rename Programming and Algorithms/Depth First Search.cpp to Programmi…
  Programming and Algorithms/Cpp/Depth First Search.cpp
Labels: hacktoberfest-accepted

#49 Rename Programming and Algorithms/Breadth First Search Algorithm.cpp …
  Programming and Algorithms/Cpp/Breadth First Search Algorithm.cpp
Labels: hacktoberfest-accepted

#58 Phrase Hunter
  Web Dev/Frontend/OOP-Game-Show-App/README.md
  Web Dev/Frontend/OOP-Game-Show-App/css/animate.css
  Web Dev/Frontend/OOP-Game-Show-App/css/styles.css
  Web Dev/Frontend/OOP-Game-Show-App/example_phrase_html.txt
  Web Dev/Frontend/OOP-Game-Show-App/images/liveHeart.png
  Web Dev/Frontend/OOP-Game-Show-App/images/lostHeart.png
  Web Dev/Frontend/OOP-Game-Show-App/index.html
  Web Dev/Frontend/OOP-Game-Show-App/js/Game.js
  Web Dev/Frontend/OOP-Game-Show-App/js/Phrase.js
  Web Dev/Frontend/OOP-Game-Show-App/js/app.js
Labels: hacktoberfest-accepted

#57 RSVP app
  Web Dev/Frontend/RSVP-App/README.md
  Web Dev/Frontend/RSVP-App/app.js
  Web Dev/Frontend/RSVP-App/css/style.css
  Web Dev/Frontend/RSVP-App/images/header-bg.jpg
  Web Dev/Frontend/RSVP-App/index.html
Labels: hacktoberfest-accepted

#61 Corporate-intranet
  Web Dev/Frontend/Corporate-Intranet/README.md
  Web Dev/Frontend/Corporate-Intranet/css/main.css
  Web Dev/Frontend/Corporate-Intranet/data/employees.json
  Web Dev/Frontend/Corporate-Intranet/data/rooms.json
  Web Dev/Frontend/Corporate-Intranet/index.html
  Web Dev/Frontend/Corporate-Intranet/js/widget.js
Labels: hacktoberfest-accepted

#63 Doggo Select
  Web Dev/Frontend/DoggoSelect/README.md
  Web Dev/Frontend/DoggoSelect/css/styles.css
  Web Dev/Frontend/DoggoSelect/images/logo.svg
  Web Dev/Frontend/DoggoSelect/index.html
  Web Dev/Frontend/DoggoSelect/js/app.js
Labels: hacktoberfest-accepted

#64 Emoji-selector
  Web Dev/Frontend/emoji-selector/README.md
  Web Dev/Frontend/emoji-selector/icons/at-solid.svg
  Web Dev/Frontend/emoji-selector/icons/bold-solid.svg
  Web Dev/Frontend/emoji-selector/icons/code-solid.svg
  Web Dev/Frontend/emoji-selector/icons/face-smile-regular.svg
  Web Dev/Frontend/emoji-selector/icons/font-solid.svg
  Web Dev/Frontend/emoji-selector/icons/italic-solid.svg
  Web Dev/Frontend/emoji-selector/icons/link-solid.svg
  Web Dev/Frontend/emoji-selector/icons/list-ol-solid.svg
  Web Dev/Frontend/emoji-selector/icons/list-solid.svg
  Web Dev/Frontend/emoji-selector/icons/microphone-solid.svg
  Web Dev/Frontend/emoji-selector/icons/paper-plane-solid.svg
  Web Dev/Frontend/emoji-selector/icons/plus-solid.svg
  Web Dev/Frontend/emoji-selector/icons/strikethrough-solid.svg
  Web Dev/Frontend/emoji-selector/icons/video-solid.svg
  Web Dev/Frontend/emoji-selector/images/api-key.png
  Web Dev/Frontend/emoji-selector/images/console.png
  Web Dev/Frontend/emoji-selector/images/endpoints.png
  Web Dev/Frontend/emoji-selector/images/open-menu.png
  Web Dev/Frontend/emoji-selector/index.html
  Web Dev/Frontend/emoji-selector/scripts/app.js
  Web Dev/Frontend/emoji-selector/styles/css/styles.css
  Web Dev/Frontend/emoji-selector/styles/css/styles.css.map
  Web Dev/Frontend/emoji-selector/styles/scss/styles.scss
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#65 Interactive form
  Web Dev/Frontend/Interactive-form/README.md
  Web Dev/Frontend/Interactive-form/css/normalize.css
  Web Dev/Frontend/Interactive-form/css/style.css
  Web Dev/Frontend/Interactive-form/img/angular.svg
  Web Dev/Frontend/Interactive-form/img/build.svg
  Web Dev/Frontend/Interactive-form/img/caret.png
  Web Dev/Frontend/Interactive-form/img/express.svg
  Web Dev/Frontend/Interactive-form/img/js.svg
  Web Dev/Frontend/Interactive-form/img/node.svg
  Web Dev/Frontend/Interactive-form/img/not-valid.svg
  Web Dev/Frontend/Interactive-form/img/npm.svg
  Web Dev/Frontend/Interactive-form/img/react.svg
  Web Dev/Frontend/Interactive-form/img/valid.svg
  Web Dev/Frontend/Interactive-form/index.html
  Web Dev/Frontend/Interactive-form/js/script.js
Labels: hacktoberfest, hacktoberfest2022

#66 added sliding registration form
  Web Dev/Frontend/Sliding registration form/README.md
  Web Dev/Frontend/Sliding registration form/css/styles.css
  Web Dev/Frontend/Sliding registration form/index.html
  Web Dev/Frontend/Sliding registration form/js/main.js
Labels: hacktoberfest-accepted

#68 Added responsive blogger website
  Web Dev/Frontend/Blogger-Website-main/LICENSE
  Web Dev/Frontend/Blogger-Website-main/README.md
  Web Dev/Frontend/Blogger-Website-main/blogers  website/blog.html
  Web Dev/Frontend/Blogger-Website-main/blogers  website/contact.html
  Web Dev/Frontend/Blogger-Website-main/blogers  website/css/contact.css
  Web Dev/Frontend/Blogger-Website-main/blogers  website/css/responsive.css
  Web Dev/Frontend/Blogger-Website-main/blogers  website/css/search.css
  Web Dev/Frontend/Blogger-Website-main/blogers  website/css/style.css
  Web Dev/Frontend/Blogger-Website-main/blogers  website/css/utils.css
  Web Dev/Frontend/Blogger-Website-main/blogers  website/img/Author_Singgle-01_generated.jpg
  Web Dev/Frontend/Blogger-Website-main/blogers  website/img/concept top angle view desktop laptop smartphone tablet newspaper office stuff horizontal copy space.jpg
  Web Dev/Frontend/Blogger-Website-main/blogers  website/img/man-hands-typing-an-article-on-a-vintage-typewriter-vector.jpg
  Web Dev/Frontend/Blogger-Website-main/blogers  website/search.html
Labels: hacktoberfest-accepted

#70 Gcd
  Programming and Algorithms/Cpp/Array/gcdOfAnArray.cpp
Labels: hacktoberfest, hacktoberfest2022

#73 Pet directory
  Web Dev/Frontend/Pet-directory/README.md
  Web Dev/Frontend/Pet-directory/css/style.css
  Web Dev/Frontend/Pet-directory/img/aussie.jpg
  Web Dev/Frontend/Pet-directory/img/dachshund.jpg
  Web Dev/Frontend/Pet-directory/img/golden.jpg
  Web Dev/Frontend/Pet-directory/img/persian.jpg
  Web Dev/Frontend/Pet-directory/img/pug.jpg
  Web Dev/Frontend/Pet-directory/img/tabby.jpg
  Web Dev/Frontend/Pet-directory/index.html
  Web Dev/Frontend/Pet-directory/js/directory.js
  Web Dev/Frontend/Pet-directory/js/pets.js
Labels: hacktoberfest-accepted

#74 Public API requests
  Web Dev/Frontend/Public-API-Requests/README.md
  Web Dev/Frontend/Public-API-Requests/css/normalize.css
  Web Dev/Frontend/Public-API-Requests/css/styles.css
  Web Dev/Frontend/Public-API-Requests/index.html
  Web Dev/Frontend/Public-API-Requests/js/scripts.js
  Web Dev/Frontend/Public-API-Requests/mockups/employee_directory.png
  Web Dev/Frontend/Public-API-Requests/mockups/employee_overlay.png
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#77 Space Explorers
  Web Dev/Frontend/Space-Explorers/README.md
  Web Dev/Frontend/Space-Explorers/css/style.css
  Web Dev/Frontend/Space-Explorers/img/profile.jpg
  Web Dev/Frontend/Space-Explorers/index.html
  Web Dev/Frontend/Space-Explorers/js/async-await.js
  Web Dev/Frontend/Space-Explorers/js/callbacks.js
  Web Dev/Frontend/Space-Explorers/js/promises-breakfast.js
  Web Dev/Frontend/Space-Explorers/js/promises.js
Labels: hacktoberfest-accepted

#71 Create HeapSort.cpp
  Programming and Algorithms/Cpp/HeapSort.cpp
Labels: hacktoberfest-accepted

#80 live-clock
  Web Dev/Frontend/Project 6LifeTimer HCJS1/images
  Web Dev/Frontend/Project 6LifeTimer HCJS1/index.html
  Web Dev/Frontend/Project 6LifeTimer HCJS1/index.js
  Web Dev/Frontend/Project 6LifeTimer HCJS1/mountain.jpg
  Web Dev/Frontend/Project 6LifeTimer HCJS1/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#81 Student list
  Web Dev/Frontend/Student-list/README.md
  Web Dev/Frontend/Student-list/css/reset.css
  Web Dev/Frontend/Student-list/css/styles.css
  Web Dev/Frontend/Student-list/examples/example-exceeds.png
  Web Dev/Frontend/Student-list/examples/example-meets.png
  Web Dev/Frontend/Student-list/img/icn-search.svg
  Web Dev/Frontend/Student-list/index.html
  Web Dev/Frontend/Student-list/js/data.js
  Web Dev/Frontend/Student-list/js/script.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#82 Restaurant-Website
  Web Dev/Frontend/Project 5/icons/delivery.png
  Web Dev/Frontend/Project 5/icons/discount.png
  Web Dev/Frontend/Project 5/icons/fresh.png
  Web Dev/Frontend/Project 5/images/grid_image1.png
  Web Dev/Frontend/Project 5/images/grid_image2.png
  Web Dev/Frontend/Project 5/images/grid_image3.png
  Web Dev/Frontend/Project 5/images/grid_image4.png
  Web Dev/Frontend/Project 5/images/grid_image5.png
  Web Dev/Frontend/Project 5/images/grid_image6.png
  Web Dev/Frontend/Project 5/images/grid_image7.png
  Web Dev/Frontend/Project 5/images/hero_image.png
  Web Dev/Frontend/Project 5/images/logo.png
  Web Dev/Frontend/Project 5/index.html
  Web Dev/Frontend/Project 5/style.css
Labels: hacktoberfest-accepted

#84 Added Hotstar Clone
  Web Dev/Frontend/Hotstar/images/add.png
  Web Dev/Frontend/Hotstar/images/disney.png
  Web Dev/Frontend/Hotstar/images/geographic.png
  Web Dev/Frontend/Hotstar/images/logo.png
  Web Dev/Frontend/Hotstar/images/marvel.png
  Web Dev/Frontend/Hotstar/images/nxt.png
  Web Dev/Frontend/Hotstar/images/pixar.png
  Web Dev/Frontend/Hotstar/images/play.png
  Web Dev/Frontend/Hotstar/images/poster1.png
  Web Dev/Frontend/Hotstar/images/poster10.png
  Web Dev/Frontend/Hotstar/images/poster11.png
  Web Dev/Frontend/Hotstar/images/poster12.png
  Web Dev/Frontend/Hotstar/images/poster2.png
  Web Dev/Frontend/Hotstar/images/poster3.png
  Web Dev/Frontend/Hotstar/images/poster4.png
  Web Dev/Frontend/Hotstar/images/poster5.png
  Web Dev/Frontend/Hotstar/images/poster6.png
  Web Dev/Frontend/Hotstar/images/poster7.png
  Web Dev/Frontend/Hotstar/images/poster8.png
  Web Dev/Frontend/Hotstar/images/poster9.png
  Web Dev/Frontend/Hotstar/images/pre.png
  Web Dev/Frontend/Hotstar/images/slider1.png
  Web Dev/Frontend/Hotstar/images/slider2.png
  Web Dev/Frontend/Hotstar/images/slider3.png
  Web Dev/Frontend/Hotstar/images/slider4.png
  Web Dev/Frontend/Hotstar/images/slider5.png
  Web Dev/Frontend/Hotstar/images/star-wars.png
  Web Dev/Frontend/Hotstar/index.html
  Web Dev/Frontend/Hotstar/index.js
  Web Dev/Frontend/Hotstar/styles.css
  Web Dev/Frontend/Hotstar/videos/disney.mp4
  Web Dev/Frontend/Hotstar/videos/geographic.mp4
  Web Dev/Frontend/Hotstar/videos/marvel.mp4
  Web Dev/Frontend/Hotstar/videos/pixar.mp4
  Web Dev/Frontend/Hotstar/videos/star-war.mp4
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#88 Code : Inverted Number Pattern
  Programming and Algorithms/Cpp/Array/Inverted_Num_p.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#90 Live-Sketch
  Programming and Algorithms/Python/livesketch.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#91 Added react-app-note-taking
  Web Dev/Frontend/react-app-note-taking/.gitignore
  Web Dev/Frontend/react-app-note-taking/README.md
  Web Dev/Frontend/react-app-note-taking/index.html
  Web Dev/Frontend/react-app-note-taking/package-lock.json
  Web Dev/Frontend/react-app-note-taking/package.json
  Web Dev/Frontend/react-app-note-taking/public/index.html
  Web Dev/Frontend/react-app-note-taking/public/styles.css
  Web Dev/Frontend/react-app-note-taking/src/components/App.jsx
  Web Dev/Frontend/react-app-note-taking/src/components/Footer.jsx
  Web Dev/Frontend/react-app-note-taking/src/components/Header.jsx
  Web Dev/Frontend/react-app-note-taking/src/components/Notes.jsx
  Web Dev/Frontend/react-app-note-taking/src/index.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#94 Sudoku Solver
  Web Dev/Frontend/SudokuSolver/README.md
  Web Dev/Frontend/SudokuSolver/favicon_io/android-chrome-192x192.png
  Web Dev/Frontend/SudokuSolver/favicon_io/android-chrome-512x512.png
  Web Dev/Frontend/SudokuSolver/favicon_io/apple-touch-icon.png
  Web Dev/Frontend/SudokuSolver/favicon_io/favicon-16x16.png
  Web Dev/Frontend/SudokuSolver/favicon_io/favicon-32x32.png
  Web Dev/Frontend/SudokuSolver/favicon_io/favicon.ico
  Web Dev/Frontend/SudokuSolver/favicon_io/site.webmanifest
  Web Dev/Frontend/SudokuSolver/index.html
  Web Dev/Frontend/SudokuSolver/js/sudoku.js
  Web Dev/Frontend/SudokuSolver/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#96 To-do list
  Web Dev/Frontend/To-do-list/README.md
  Web Dev/Frontend/To-do-list/app.js
  Web Dev/Frontend/To-do-list/css/style.css
  Web Dev/Frontend/To-do-list/index.html
  Web Dev/Frontend/To-do-list/temp.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#92 BestForSearch-Algo
  sorting/BestforSearch.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#99 Dice roll app
  App Dev/Android/DiceRoll/.gitignore
  App Dev/Android/DiceRoll/.idea/.gitignore
  App Dev/Android/DiceRoll/.idea/.name
  App Dev/Android/DiceRoll/.idea/compiler.xml
  App Dev/Android/DiceRoll/.idea/gradle.xml
  App Dev/Android/DiceRoll/.idea/misc.xml
  App Dev/Android/DiceRoll/app/.gitignore
  App Dev/Android/DiceRoll/app/build.gradle
  App Dev/Android/DiceRoll/app/proguard-rules.pro
  App Dev/Android/DiceRoll/app/src/androidTest/java/com/example/diceroll/ExampleInstrumentedTest.kt
  App Dev/Android/DiceRoll/app/src/main/AndroidManifest.xml
  App Dev/Android/DiceRoll/app/src/main/java/com/example/diceroll/MainActivity.kt
  App Dev/Android/DiceRoll/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  App Dev/Android/DiceRoll/app/src/main/res/drawable/dice_1.png
  App Dev/Android/DiceRoll/app/src/main/res/drawable/dice_2.png
  App Dev/Android/DiceRoll/app/src/main/res/drawable/dice_3.png
  App Dev/Android/DiceRoll/app/src/main/res/drawable/dice_4.png
  App Dev/Android/DiceRoll/app/src/main/res/drawable/dice_5.png
  App Dev/Android/DiceRoll/app/src/main/res/drawable/dice_6.png
  App Dev/Android/DiceRoll/app/src/main/res/drawable/ic_launcher_background.xml
  App Dev/Android/DiceRoll/app/src/main/res/layout/activity_main.xml
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  App Dev/Android/DiceRoll/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  App Dev/Android/DiceRoll/app/src/main/res/values-night/themes.xml
  App Dev/Android/DiceRoll/app/src/main/res/values/colors.xml
  App Dev/Android/DiceRoll/app/src/main/res/values/strings.xml
  App Dev/Android/DiceRoll/app/src/main/res/values/themes.xml
  App Dev/Android/DiceRoll/app/src/main/res/xml/backup_rules.xml
  App Dev/Android/DiceRoll/app/src/main/res/xml/data_extraction_rules.xml
  App Dev/Android/DiceRoll/app/src/test/java/com/example/diceroll/ExampleUnitTest.kt
  App Dev/Android/DiceRoll/build.gradle
  App Dev/Android/DiceRoll/gradle.properties
  App Dev/Android/DiceRoll/gradle/wrapper/gradle-wrapper.jar
  App Dev/Android/DiceRoll/gradle/wrapper/gradle-wrapper.properties
  App Dev/Android/DiceRoll/gradlew
  App Dev/Android/DiceRoll/gradlew.bat
  App Dev/Android/DiceRoll/settings.gradle
  Web Dev/Frontend/parallax_effect/1.png
  Web Dev/Frontend/parallax_effect/2.png
  Web Dev/Frontend/parallax_effect/3.png
  Web Dev/Frontend/parallax_effect/4.png
  Web Dev/Frontend/parallax_effect/main.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#100 Sentiment Analysis Project Added
  AI and ML/Sentiment-Analysis/README.md
  AI and ML/Sentiment-Analysis/app.py
  AI and ML/Sentiment-Analysis/templates/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#102 nft-minter project added
  .gitmodules
  Blockchain/NFT-MINTER-CLIENT/.gitignore
  Blockchain/NFT-MINTER-CLIENT/README.md
  Blockchain/NFT-MINTER-CLIENT/package-lock.json
  Blockchain/NFT-MINTER-CLIENT/package.json
  Blockchain/NFT-MINTER-CLIENT/public/favicon.ico
  Blockchain/NFT-MINTER-CLIENT/public/index.html
  Blockchain/NFT-MINTER-CLIENT/public/logo192.png
  Blockchain/NFT-MINTER-CLIENT/public/logo512.png
  Blockchain/NFT-MINTER-CLIENT/public/manifest.json
  Blockchain/NFT-MINTER-CLIENT/public/robots.txt
  Blockchain/NFT-MINTER-CLIENT/src/App.css
  Blockchain/NFT-MINTER-CLIENT/src/App.js
  Blockchain/NFT-MINTER-CLIENT/src/App.test.js
  Blockchain/NFT-MINTER-CLIENT/src/assets/twitter-logo.svg
  Blockchain/NFT-MINTER-CLIENT/src/assets/weth.png
  Blockchain/NFT-MINTER-CLIENT/src/components/AbstractList.css
  Blockchain/NFT-MINTER-CLIENT/src/components/AbstractList.js
  Blockchain/NFT-MINTER-CLIENT/src/components/CollectionCard.css
  Blockchain/NFT-MINTER-CLIENT/src/components/CollectionCard.js
  Blockchain/NFT-MINTER-CLIENT/src/components/Main.css
  Blockchain/NFT-MINTER-CLIENT/src/components/Main.js
  Blockchain/NFT-MINTER-CLIENT/src/index.css
  Blockchain/NFT-MINTER-CLIENT/src/index.js
  Blockchain/NFT-MINTER-CLIENT/src/logo.svg
  Blockchain/NFT-MINTER-CLIENT/src/reportWebVitals.js
  Blockchain/NFT-MINTER-CLIENT/src/setupTests.js
  Blockchain/NFT-MINTER-CLIENT/src/utils/MyEpicNFT.json
  Blockchain/NFT-MINTER-SMART-CONTRACT/.gitignore
  Blockchain/NFT-MINTER-SMART-CONTRACT/README.md
  Blockchain/NFT-MINTER-SMART-CONTRACT/contracts/MyEpicNFT.sol
  Blockchain/NFT-MINTER-SMART-CONTRACT/contracts/libraries/Base64.sol
  Blockchain/NFT-MINTER-SMART-CONTRACT/package-lock.json
  Blockchain/NFT-MINTER-SMART-CONTRACT/package.json
  Blockchain/NFT-MINTER-SMART-CONTRACT/scripts/deploy.js
  Blockchain/NFT-MINTER-SMART-CONTRACT/scripts/run.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#104 hashcode_generator
  App Dev/Flutter/snake_game/pubspec.lock
  Python Projects/hashcode_generator.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#107 Add files via upload
  Web Dev/Frontend/index.html
  Web Dev/Frontend/logic.js
  Web Dev/Frontend/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#112 Create towerOfHanoi.java
  Programming and Algorithms/java/towerOfHanoi.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#119 Cryptosystem
  Python Projects/cryptosystem.py
  sorting/PigeonSort.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#115 Create Pythagorean_triplet.java
  Programming and Algorithms/java/Pythagorean_triplet.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#122 Multiple stack
  Programming and Algorithms/Cpp/MStk.cpp
Labels: hacktoberfest, hacktoberfest2022

#124 Update README.md
  README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#131 Added Email Spam Detection Code
  AI and ML/Email-Spam-Detection/Readme.md
  AI and ML/Email-Spam-Detection/app.py
  AI and ML/Email-Spam-Detection/spam.csv
  AI and ML/Email-Spam-Detection/templates/home.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#136 Added URLShortener
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/__init__.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/__pycache__/__init__.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/__pycache__/settings.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/__pycache__/urls.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/__pycache__/wsgi.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/asgi.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/settings.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/urls.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/wsgi.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__init__.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__pycache__/__init__.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__pycache__/admin.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__pycache__/apps.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__pycache__/models.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__pycache__/urls.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/__pycache__/views.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/admin.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/apps.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/migrations/0001_initial.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/migrations/__init__.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/migrations/__pycache__/0001_initial.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/migrations/__pycache__/__init__.cpython-310.pyc
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/models.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/static/Rebrandly.png
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/static/style.css
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/templates/home.html
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/templates/index.html
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/tests.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/urls.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/URLShortener/views.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/db.sqlite3
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/manage.py
  Web Dev/Full Stack/URLShortener/Readme.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#140 Adding background subtraction code
  Programming and Algorithms/Python/bckrnd_sub.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#125 Create quickSort.cpp
  Programming and Algorithms/Cpp/Array/quickSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#128 added floyd warshall
  Programming and Algorithms/Cpp/Floyd_Warshall.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#135 Insertion sort
  sorting/insertion_sort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#146 Update settings.py
  Web Dev/Full Stack/URLShortener/DjangoWorkshop/DjangoWorkshop/settings.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#120 GestureDetection
  Python Projects/GestureDetection.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#147 Create Doraemon.py
  Python Projects/Doraemon.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#137 Added Graph Algorithms
  Programming and Algorithms/Cpp/Graph/BellmannFord.cpp
  Programming and Algorithms/Cpp/Graph/Dijkstra.cpp
  Programming and Algorithms/Cpp/Graph/DisjointSetUnion.cpp
  Programming and Algorithms/Cpp/Graph/FloyddWarshall.cpp
  Programming and Algorithms/Cpp/Graph/KruskalsMST.cpp
  Programming and Algorithms/Cpp/Graph/PrimsMST.cpp
  Programming and Algorithms/Cpp/Graph/TopologicalSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#149 Create RestaurantManagementSystem.py
  Python Projects/RestaurantManagementSystem.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#138 Create vector.cpp
  Programming and Algorithms/Cpp/vector.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#141 Remove Consecutive Duplicates
  Programming and Algorithms/Cpp/Remove_Consecutive_Duplicates.cpp
  Programming and Algorithms/Cpp/Wave Print.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#154 Hey, I have added rotate array by d elements solution
  Programming and Algorithms/Cpp/Array/rotatearr.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#153 Create calculator.py
  Python Projects/calculator.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#155 Hey, I have added the code of Push zeros to end of array
  Programming and Algorithms/Cpp/Array/push0toend.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#158 Solution3 added
  Programming and Algorithms/java/Palindrome Number
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#170 create first and last position of element in sorted array
  Programming and Algorithms/Cpp/Array/FirstAndLastPositionOfElementSortedArray
  Programming and Algorithms/Cpp/Array/LinearSearch.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#186 Create SelectionSort.cpp
  Programming and Algorithms/Cpp/Array/SelectionSort.cpp
Labels: hacktoberfest, hacktoberfest2022

#188 linked list,stack
  decimal to binary.c
  dynamic queue.c
  dynamic stack.c
  polynomial subtraction.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#189 Parenthesis checker
  Parenthesis Checker
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#190 Create queueUsingStack
  Programming and Algorithms/Cpp/Array/queueUsingStack
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#191 LCA Agorithm
  Programming and Algorithms/Cpp/Graph/LCA-Graph-algorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#192 Real Time Chat Application With Different Rooms
  Web Dev/Full Stack/Super_Chat-master/README.md
  Web Dev/Full Stack/Super_Chat-master/package-lock.json
  Web Dev/Full Stack/Super_Chat-master/package.json
  Web Dev/Full Stack/Super_Chat-master/public/chat.html
  Web Dev/Full Stack/Super_Chat-master/public/css/style.css
  Web Dev/Full Stack/Super_Chat-master/public/index.html
  Web Dev/Full Stack/Super_Chat-master/public/js/app.js
  Web Dev/Full Stack/Super_Chat-master/public/js/main.js
  Web Dev/Full Stack/Super_Chat-master/public/particles.json
  Web Dev/Full Stack/Super_Chat-master/server.js
  Web Dev/Full Stack/Super_Chat-master/utils/messages.js
  Web Dev/Full Stack/Super_Chat-master/utils/users.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#193 Added a template for Login-Signup
  Web Dev/Full Stack/Register_Login_Boilerplate-master/app.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/config/auth.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/config/keys.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/config/passport.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/model/User.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/package-lock.json
  Web Dev/Full Stack/Register_Login_Boilerplate-master/package.json
  Web Dev/Full Stack/Register_Login_Boilerplate-master/routes/index.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/routes/user.js
  Web Dev/Full Stack/Register_Login_Boilerplate-master/views/dashboard.ejs
  Web Dev/Full Stack/Register_Login_Boilerplate-master/views/layout.ejs
  Web Dev/Full Stack/Register_Login_Boilerplate-master/views/login.ejs
  Web Dev/Full Stack/Register_Login_Boilerplate-master/views/partials/messages.ejs
  Web Dev/Full Stack/Register_Login_Boilerplate-master/views/register.ejs
  Web Dev/Full Stack/Register_Login_Boilerplate-master/views/welcome.ejs
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#194 E-Commerse Website
  Web Dev/Full Stack/E-Commerce-website.-master/README.md
  Web Dev/Full Stack/E-Commerce-website.-master/app.js
  Web Dev/Full Stack/E-Commerce-website.-master/bin/www
  Web Dev/Full Stack/E-Commerce-website.-master/config/passport.js
  Web Dev/Full Stack/E-Commerce-website.-master/models/cart.js
  Web Dev/Full Stack/E-Commerce-website.-master/models/order.js
  Web Dev/Full Stack/E-Commerce-website.-master/models/product.js
  Web Dev/Full Stack/E-Commerce-website.-master/models/user.js
  Web Dev/Full Stack/E-Commerce-website.-master/package-lock.json
  Web Dev/Full Stack/E-Commerce-website.-master/package.json
  Web Dev/Full Stack/E-Commerce-website.-master/public/javascripts/checkout.js
  Web Dev/Full Stack/E-Commerce-website.-master/public/stylesheets/style.css
  Web Dev/Full Stack/E-Commerce-website.-master/routes/index.js
  Web Dev/Full Stack/E-Commerce-website.-master/routes/user.js
  Web Dev/Full Stack/E-Commerce-website.-master/seed/product-seeder.js
  Web Dev/Full Stack/E-Commerce-website.-master/views/error.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/layouts/layout.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/partials/header.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/shop/checkout.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/shop/index.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/shop/shopping-cart.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/user/profile.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/user/signin.hbs
  Web Dev/Full Stack/E-Commerce-website.-master/views/user/signup.hbs
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#196 selection sort
  Programming and Algorithms/Cpp/Array/selection sort
Labels: hacktoberfest, hacktoberfest-accepted

#197 Create add.py
  Programming and Algorithms/Python/add.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#198 changed the color and size
  UI & UX/Tacos-By-Roscoe-Delivery-Form/style.css
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#199 added merge sort
  Programming and Algorithms/Cpp/mergesort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#201 uploading a game code
  Python Projects/Stone Paper Project/stonepaperscissor_basic.py
  Python Projects/Stone Paper Project/stonepaperscissor_interfaceversion.py
  Python Projects/Stone Paper Project/stonepaperscissor_voiceinteractive.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#200 added achievement section
  Web Dev/Frontend/Basic-Portfolio/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#185 Create LinearSearch.cpp
  Programming and Algorithms/Cpp/Array/Linear_search.cpp
Labels: hacktoberfest, hacktoberfest2022

#151 Create PrernaRathore.py
  Python Projects/PrernaRathore.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#202 Tindog index.html
  Web Dev/Frontend/TinDog-Start-master/index.html
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
